### ISSUE TITLE
Ember CLI plugin order matters with ssh-tunnel

### ISSUE THREAD

**Issue by nbibler** [mwpastore/ember-cli-deploy-sql#3]
When using `ember-cli-deploy-ssh-tunnel` with `ember-cli-deploy-sql` it is imperative that the tunnel be established _before_ the sql plugin attempts to setup. Otherwise, all deploy activities will fail when they fail to connect to the sql instances (incorrectly attempting to connect to a `localhost` server, often).

With current Ember CLI, the load order can be set by developers in the `config/deploy.js` file with:

```javascript
var ENV = {
  pipeline: {
    runOrder: {
      'sql': { after: 'ssh-tunnel' }
    },
  },
};
```

This should be at least documented in the README if you want developers to manually perform this action. If you're willing to update this plugin, [your `index.js`](https://github.com/mwpastore/ember-cli-deploy-sql/blob/5cf004c7be75e5517662f37937c84fa9c65448e0/index.js#L25) can be updated to add a `runAfter`:

```javascript
  createDeployPlugin: function(options) {
    var DeployPlugin = BasePlugin.extend({
      runAfter: 'ssh-tunnel',
```

Although, that would likely require the developer use `ssh-tunnel` which may be a stretch. README seems to be the safest approach, IMHO.

**Comment by mwpastore** [comment]
Thanks @nbibler!
